---
title: 예외처리
excerpt: 예외처리
categories: Java
tags: [codestates, Java]
toc: true
toc_sticky: true
author_profile: true
sidebar_main: true
published : true
---
## 예외 처리(Exception Handling)
- 예기치 않은 에러에 대응할 수 있는 코드를 미리 사전에 작성하여 프로그램의 비정상적인 종료를 방지하고, 정상적인 실행 상태를 유지하는 것
- 에러의 발생 시점에 따라 컴파일 에러와 런타임 에러로 구분
  - 코드에 논리적인 오류가 있을 경우에 발생하는 논리적 에러(Logical Error)도 존재

### 컴파일 에러(Compile Time Error)
- 컴파일 시, 발생하는 에러
- 문법적인 문제를 가리키는 신택스(syntax) 오류로부터 발생하기 때문에 신택스 에러(Systax Errors)라고도 부름
  - 세미콜론 생략, 오탈자, 잘못된 자료형, 잘못된 포맷 등 
- 자바 컴파일러가 오류를 감지하여, 손쉽게 발견 및 수정이 가능

### 런타임 에러(Run Time Error)
- 런타임 시, 발생하는 에러
- 컴퓨터가 수행할 수 없는 작업을 요청할 때 발생
- 프로그램이 실행 시, 자바 가상 머신(JVM)에 의해 감지

### 에러와 예외

#### 에러
- 한번 발생하면 복구하기 어려운 수준의 심각한 오류
  - 메모리 부족(OutOfMemoryError), 스택오버플로우(StackOverflowError) 등

#### 예외
- 잘못된 사용 또는 코딩으로 인한 상대적으로 미약한 수준의 오류
- 코드 수정 등을 통해 수습 가능

### 예외 클래스의 상속 계층도
![image](https://github.com/JSooCha/JSooCha.github.io/assets/90169862/3adf1205-2b21-40ba-a821-4ea72bb7b93c)
- 자바의 모든 에러와 예외 클래스는 Throwable 클래스로부터 확장됨
- 모든 예외의 최고 상위 클래스인 Exception 클래스는 일반 예외 클래스와 실행 예외 클래스로 나뉨

#### 일반 예외 클래스(Exception)
- RuntimeException 클래스와 그 하위 클래스를 제외한, 모든 Exception 클래스와 그 하위 클래스
- checked 예외라고도 부름
  - 컴파일러가 코드 실행 전에 예외 처리 코드 여부를 검사
- 사용자의 실수로 발생하는 경우가 많음
  - 잘못된 클래스명(ClassNotFoundException)이나 데이터 형식(DataFormatException) 등

#### 실행 예외 클래스(Runtime Exception)
- 런타임 시 발생하는 RuntimeException 클래스와 그 하위클래스
-  unchecked 예외라고도 부름
  - 컴파일러가 예외 처리 코드 여부를 검사하지 않음
- 개발자의 실수로 발생하는 경우가 많고, 자바 문법 요소와 관련이 있음
  - 클래스 간 형변환 오류(ClassCastException), 벗어난 배열 범위 지정(ArrayIndexOutOfBoundsException), 값이 null인 참조변수 사용(NullPointerException) 등 

### try - catch문
```java
try {
    // 예외가 발생할 가능성이 있는 코드
} 
catch (ExceptionType1 e1) {
    // ExceptionType1 유형의 예외 발생 시 실행할 코드
} 
catch (ExceptionType2 e2) {
    // ExceptionType2 유형의 예외 발생 시 실행할 코드
} 
finally {
    // 생략 가능
    // 예외 발생 여부와 상관없이 항상 실행
}
```
- ```try { }``` : 예외가 발생할 가능성이 있는 코드
  - 작성한 코드가 예외 없이 정상적으로 실행되면 아래 catch 블록은 실행되지 않고 finally 블록이 실행
- ```catch { }``` : 예외가 발생할 때 실행되는 코드
  - 여러 종류의 예외 처리
    - 각기 다른 예외를 하나 이상의 catch 블록을 사용하여 처리
    - ```instanceOf``` 연산자를 통해 생성된 예외 클래스의 인스턴스가 조건과 일치하는지 판단
    - 모든 예외를 받을 수 있는 Exception 클래스 하나로도 처리 가능
  - catch 블록이 여러 개인 경우, 일치하는 하나의 catch 블록만이 실행되며, 예외처리 코드가 종료되거나 finally 블록으로 넘어감
    - catch 블록은 위에서부터 순차적으로 검사를 진행하기 때문에, 구체적인 예외 클래스인 하위클래스를 먼저 위에 배치하여 상위 예외 클래스가 먼저 실행되지 않도록 방지해야 함

```java
public class RuntimeExceptionTest {
    public static void main(String[] args) {
        try {
            System.out.println("[소문자 알파벳을 대문자로 출력하는 프로그램]");
            printMyName(null); // (1) 예외 발생
            printMyName("abc"); // 이 코드는 실행되지 않고 catch 문으로 이동
        } 
        catch (ArithmeticException e) {
            System.out.println("ArithmeticException 발생!"); // (2) 첫 번째 catch문
        } 
        catch (NullPointerException e) { // (3) 두 번째 catch문
            System.out.println("NullPointerException 발생!"); 
            System.out.println("e.getMessage: " + e.getMessage()); // (4) 예외 정보를 얻는 방법 - 1
            System.out.println("e.toString: " + e.toString()); // (4) 예외 정보를 얻는 방법 - 2
            e.printStackTrace(); // (4) 예외 정보를 얻는 방법 - 3
        } 
        finally {
            System.out.println("[프로그램 종료]"); // (5) finally 문
        }
    }

    static void printMyName(String str) {
        String upperCaseAlphabet = str.toUpperCase();
        System.out.println(upperCaseAlphabet);
    }
}
```


### 예외 전가
- 예외를 호출한 곳으로 다시 예외를 떠넘기는 방법
- ```throws``` 키워드 뒤에 발생할 수 있는 예외들을 나열
- main() 메서드에서도 사용 가능
  - 자바 JVM이 최종적으로 예외의 내용을 콘솔에 출력하여 예외 처리 수행
  
```java
반환타입 메서드명(매개변수, ...) throws 예외클래스1, 예외클래스2, ... { }

void ExampleMethod() throws Exception { }
```

```java
public class ThrowExceptionTest {
    public static void main(String[] args) {
        try {
            throwException();
        } catch (ClassNotFoundException e) {
            System.out.println(e.getMessage());
        }
    }

    static void throwException() throws ClassNotFoundException, NullPointerException {
        Class.forName("java.lang.StringX");
    }
}

//출력값
java.lang.StringX
```
- 잘못된 코드 작성으로 인한 런타임 에러 발생
- 해당 예외가 발생한 메서드 안에서 처리하지 않고, 메서드를 호출한 곳으로 다시 떠넘김
  - 예외 처리의 책임은 throwException 메서드가 아닌 main 메서드가 지게 됨

### 의도적인 예외 발생
- ```throw``` 키워드를 사용하면 예외를 의도적으로 발생시킬 수 있음
```java
public class ExceptionTest {
    public static void main(String[] args) {
        try {
            Exception intendedException = new Exception("의도된 예외 만들기");
            throw intendedException;
        } catch (Exception e) {
            System.out.println("의도적인 예외 발생");
        }
    }
}

//출력값
의도적인 예외 발생
```
